### ISSUE TITLE
Unstable and freezing work of an application after updating

### ISSUE THREAD

**Issue by ComradeMashkov** [pelicanmapping/rocky#64]
Hey, Glenn. I was trying to updated to main (16ce49e1da2b6ad069cad851b5b4a7c05fdd7292) from my last version of Rocky (7675ec5724665ec4d80852a3fb9ec003e7e37cfa). I tried to, fixed some methods namings, API calls etc. but issued a problem of an application being too laggy and after few seconds it stuck (see video 1). 

At first glance I thought that it was a problem in my application, but I tried to launch a rocky_demo executable and it worked the same way. Meanwhile I also tried to launch rocky_engine and it lead to an unpredictable result: it worked as fine as always (see video 2). I also tried to install newest vsg (1.1.8), vsgXchange (master) and vsgImGui (master) but this didn't solve the issue.

So I have a guess: ImGui or vsgImGui is broken, because rocky_engine works just fine and it has no ImGui, meanwhile rocky_demo works pretty bad. Do you know what is the root of the problem? It takes a while to reinstall this bunch of rendering libraries and APIs so I didn't manage to do a lot. Thanks for your help!

Video 1: https://imgur.com/a/OCPLRL6
Video 2: https://imgur.com/a/0KaiVXI

**Comment by ComradeMashkov** [comment]
Just tried commit d00548d2a7216ae8dcaa6b1d01d5c1287febae0b, still the same...

**Comment by gwaldron** [comment]
For now, we switched the Application construct to use "on demand" rendering mode by default. In "on demand" mode, new frames only render if something has potentially changed.

The Stats display does not update when frames are not rendering, so it _appears_ to freeze. Updating the Stats readout to work better in this mode is TBD.

You can switch it back to continuous-rendering by opening the Rendering panel and unchecking "Render on demand".

(`rocky_engine` will still render continuously by default because it does not use the `Application` object.)

**Comment by ComradeMashkov** [comment]
Oh, I'm sorry for me didn't see it coming. Will be more attentive next time. I'll check it out and give a response here.

**Comment by ComradeMashkov** [comment]
Well it works for me now. Thanks!
